# Use an official lightweight Python image
FROM python:3.10-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the source code into the container
COPY ./src /app/src

# Command to run the Celery worker for asynchronous NLP tasks
CMD ["celery", "-A", "src.api.worker.celery_app", "worker", "--loglevel=info"]